### ISSUE TITLE
I don't understand, please help me

### ISSUE THREAD

**Issue by dgoodlad** [joho/jrb#4]
I can't seem to get this working. I get this error

```
$ ruby
ruby: command not found
```

What can I do?

**Comment by DylanFM** [comment]
Ruby only works via Siri, IIRC.

**Comment by dgoodlad** [comment]
I can't see Siri on the Google Play store, where do I install?

**Comment by yachi** [comment]
make sure your device is rooted and has busybox installed

**Comment by floere** [comment]
You need to upgrade to ice cream sandwich. I'm pretty sure you can get that at any 7-11.

**Comment by chendo** [comment]
But I'm lactose intolerant :(

**Comment by floere** [comment]
Use `--no-lactose` on the command line. `-X256` seems to help as well.
